name: Assign Issue

on:
  issues:
    types: [opened, edited]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Team Member
        if: startsWith(github.event.issue.labels.*.name, 'team-')
        uses: peter-evans/assign-issues@v2.2.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ join(github.event.issue.labels.*.name) }}
